### ISSUE TITLE
Input validations

### ISSUE THREAD

**Issue by chiapet92** [xzhang395/Stalk-Market#1]
All text boxes are free form, and should require at least basic data validation.

**Comment by chiapet92** [comment]
basic validation done: b902309cf406665a8f39d9d9907b0c908064f886

**Comment by davidpchi** [comment]
Note that the scrubInput method does not properly scrub the input. I have noted that here:

https://github.com/xzhang395/Stalk-Market/pull/13

I ended up closing that PR because migrating to RNW should resolve the XSS issues.

**Comment by chiapet92** [comment]
with https://github.com/xzhang395/Stalk-Market/commit/9c102d75111a53a328207b09f18c962e4f385658 commit, each user cannot generate multiple data entries during the same period of time, which effectively contains the ability of a single malicious user to generate lots of bad data. 

This issue can effectively be considered as closed.
