### ISSUE TITLE
Clients should only submit the form once, probably

### ISSUE THREAD

**Issue by chiapet92** [xzhang395/Stalk-Market#11]

**Comment by davidpchi** [comment]
It depends on what you want to achieve here:
- you could put restrictions on your server where a user cannot update the database more than 1 time an hour, etc. 
- Or have the client restrict multiple submissions within a single session (refresh clears this) using a persisted redux store
- Use cookies

**Comment by chiapet92** [comment]
There's an outstanding [issue to integrate with google auth](https://github.com/xzhang395/Stalk-Market/issues/10), which would serve as a basis to allow each client only have a single entry within a half-day period. ANy further updates would update their existing entry rather than write a new entry. 

Currently, the issue at hand is that there's a lack of response to the client when they click submit, which means that they run the risk of submitting multiple times if they click multiple times by accident.

**Comment by chiapet92** [comment]
Completed w/ https://github.com/xzhang395/Stalk-Market/commit/8aca9ceda87071f2ce010e155c7fcc1c45d7f96f
