### ISSUE TITLE
Timezone should be taken into account

### ISSUE THREAD

**Issue by j-zhao** [xzhang395/Stalk-Market#17]
Data is only relevant if timezone is taken into account, otherwise there will be price discrepancies. Each price should have its own TTL

**Comment by chiapet92** [comment]
Hi @j-zhao , thanks for cutting an issue. 

Are you seeing this as an actual bug or just an FYI? The TTL has already been implemented in a previous fix.

**Comment by j-zhao** [comment]
Feature request for timezones

**Comment by chiapet92** [comment]
What exactly do you want to see regarding timezones? The application already handles:

1) local time of the user and properly sets the expiration time based on that value. 
2) calculation of the expiration time based on the expiration of the highest score in ISO time

If the application doesn't handle anything specifically, please detail out that case.

**Comment by j-zhao** [comment]
I see what you mean, this wasn't obvious, so a row is only displayed if
it's not expired? Feel free to close the issue.

**Comment by chiapet92** [comment]
The current code performs a filter on retrieval, so none of the expired entries are ever displayed. 

https://github.com/xzhang395/Stalk-Market/blob/8f8eb9e08fc7acd50e8452600d4846f148b22dde/src/containers/App.js#L36-L38

Closing issue.

**Comment by chiapet92** [comment]
Completed in https://github.com/xzhang395/Stalk-Market/issues/5
