### ISSUE TITLE
Content of this git repo does not match the site linked 

### ISSUE THREAD

**Issue by moutonnoireu** [xzhang395/Stalk-Market#3]
Hello,

The content of this repo does not match https://stalk-market-4dc91.firebaseapp.com/ is it another project ?

Thanks in advance.

**Comment by chiapet92** [comment]
It's the same project. My gf and I spun this up project last night, but turned it to private after I realized that we published the API key for firebase db. 

I guess since it's already out there, we can re-open this as public, and spin up another datastore to after we implement auth.
